spring.application.name=oliveiras-multimarcas
spring.profiles.active=${PROFILE:dev}

# --- IMPORTANTE: Configurações do JWT (que estavam faltando) ---
secret_access=${JWT_ACCESS_SECRET}
expiration_access=${JWT_EXPIRATION_ACCESS}
secret_refresh=${JWT_REFRESH_SECRET}
expiration_refresh=${JWT_EXPIRATION_REFRESH}

aws.accessKey=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.bucketName=${AWS_BUCKET_NAME}

recaptcha.secret=${RECAPTCHA_SECRET_KEY}