server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=5

secret_access=${JWT_ACCESS_SECRET}
expiration_access=${JWT_EXPIRATION_ACCESS}

secret_refresh=${JWT_REFRESH_SECRET}
expiration_refresh=${JWT_EXPIRATION_REFRESH}

recaptcha.secret=${RECAPTCHA_SECRET_KEY}

aws.accessKey=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.bucketName=${AWS_BUCKET_NAME}

app.allowed-origins=${ALLOWED_ORIGINS}

management.endpoints.web.exposure.include=health

server.error.include-message=always
server.error.include-binding-errors=always