spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

secret_access=${JWT_ACCESS_SECRET}
expiration_access=${JWT_EXPIRATION_ACCESS}

secret_refresh=${JWT_REFRESH_SECRET}
expiration_refresh=${JWT_EXPIRATION_REFRESH}

recaptcha.secret=${RECAPTCHA_SECRET_KEY}

aws.accessKey=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.bucketName=${AWS_BUCKET_NAME}

cors.origins=${ALLOWED_ORIGINS}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
